server:
  port: 8079
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: development

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp

sys:
  ver: 1.0.0
